SELECT T.CODIGO_TAREFA,
       T.TITULO,
       T.DESCRICAO,
       T.DATA_CRIACAO,
       T.DATA_CONCLUSAO,
       (T.DATA_CONCLUSAO - T.DATA_CRIACAO) AS TEMPO_GASTO,
       U.NOME AS USUARIO,
       T.CPF
       FROM TAREFAS T
       INNER JOIN USUARIOS U
       ON T.CPF = U.CPF
       WHERE T.STATUS = 1
       ORDER BY T.DATA_CONCLUSAO
