CREATE TABLE LABDATABASE.USUARIOS (
    CPF VARCHAR2(11) NOT NULL,
    NOME VARCHAR2(255) NOT NULL,
    CONSTRAINT USUARIOS_PK PRIMARY KEY (CPF)
);

CREATE TABLE LABDATABASE.TAREFAS (
    CODIGO_TAREFA INTEGER NOT NULL,
    TITULO VARCHAR2(255) NOT NULL,
    DESCRICAO VARCHAR2(255) NOT NULL,
    DATA_CRIACAO TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    DATA_CONCLUSAO TIMESTAMP NULL,
    STATUS NUMERIC(1) DEFAULT 0 NOT NULL, -- 0 = Pendente, 1 = Concluida
    CPF VARCHAR2(11) NOT NULL,
    CONSTRAINT TAREFAS_PK PRIMARY KEY (CODIGO_TAREFA)
);

CREATE SEQUENCE LABDATABASE.TAREFAS_CODIGO_TAREFA_SEQ;

ALTER TABLE LABDATABASE.TAREFAS ADD CONSTRAINT USUARIOS_TAREFAS_FK
FOREIGN KEY (CPF)
REFERENCES LABDATABASE.USUARIOS (CPF)
NOT DEFERRABLE;

GRANT ALL ON LABDATABASE.TAREFAS TO LABDATABASE;
GRANT ALL ON LABDATABASE.USUARIOS TO LABDATABASE;




